apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: business-automation-operator
rules:
- apiGroups:
  - console.openshift.io
  resources:
  - consolelinks
  - consoleyamlsamples
  verbs:
  - get
  - create
  - update
  - delete
