kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: business-automation-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: business-automation-operator
subjects:
  - kind: ServiceAccount
    name: business-automation-operator
